Feature/interpreter/sensor detection range
tier4/scenario_simulator_v2 pull request #1056
Opened 2023-07-28 20:57 UTC by kyoichi-sugahara

## Types of PR

- [x] New Features
- [x] Upgrade of existing features
- [ ] Bugfix

## Description

### New features
- New feature of setting detection sensor range

### Ugrade of existion features
- change behavior based on the parameter described in the scenario file

Current implementation::

| detectionSensorRange [m] | isClairvoyant   | detectedObjects                                 |
| ------------------------ | --------------- | ----------------------------------------------- |
| 300 [m] (default)        | false (default) | Objects detected by LiDAR raycast in 100m range |
| 300 [m] (default)        | true            | All Objects within a 300m range                 |
| 10 [m]                   | false (default) | Objects detected by lidar raycast in 100m range |
| 10 [m]                   | true            | All Objects within a 10m range range             |

After this PR:

| detectionSensorRange [m] | isClairvoyant   | detectedObjects                                     | detectable objects |
| ------------------------ | --------------- | --------------------------------------------------- | ------------------ |
| 300 [m] (default)        | false (default) | Objects detected by lidar raycast in **300m** range | A                  |
| 300 [m] (default)        | true            | All Objects within a **300m** range                 | A, B, C            |
| 10 [m]                   | false (default) | Objects detected by lidar raycast in **10m** range   | A                  |
| 10 [m]                   | true            | All Objects within a **10m** range range             | B                  |

![image](https://github.com/tier4/scenario_simulator_v2/assets/32741405/10db77ea-7e32-4311-8433-700955e6614d)

## How to review this PR.

I will prepare scenario file.

## Others

2023-08-02 03:14 UTC, hakuturu583 requested changes

2023-08-02 03:14 UTC, hakuturu583 commented on simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/raycaster.hpp
>      std::string frame_id, const rclcpp::Time & stamp, geometry_msgs::msg::Pose origin,
```suggestion
    const std::string & frame_id, const rclcpp::Time & stamp, const geometry_msgs::msg::Pose & origin,
```

2023-08-03 11:17 UTC, kyoichi-sugahara commented on simulation/simulation_interface/proto/simulation_api_schema.proto
> +  bool detect_all_objects_in_range = 5;             // If false, simulator publish detection result only lidar ray was hit. If true, simulator publish detection result of entities in range.
changed in https://github.com/tier4/scenario_simulator_v2/pull/1056/commits/4656077273ae3e24a4b794a7326251a1339d63b5

2023-08-03 11:17 UTC, kyoichi-sugahara commented on simulation/simulation_interface/proto/simulation_api_schema.proto
> +  bool detect_all_objects_in_range = 8;     // If false, simulator publish detection result only lidar ray was hit. If true, simulator publish detection result of entities in range.
deleted this parameter in https://github.com/tier4/scenario_simulator_v2/pull/1056/commits/4656077273ae3e24a4b794a7326251a1339d63b5

2023-08-04 01:00 UTC, hakuturu583 commented
@kyoichi-sugahara Thank you for fixing problems, but the build test was failed.

2023-08-08 17:45 UTC, kyoichi-sugahara commented
@hakuturu583 
I solved the failing of the build test. Thank you for checking!

2023-08-23 03:13 UTC, hakuturu583 approved these changes

2023-08-23 03:13 UTC, hakuturu583 commented on simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
> +  return distance <= range;
```suggestion
  return std::hypot(point1.x() - point2.x(), point1.y() - point2.y(), point1.z() - point2.z()) <=
         range;
```

2023-08-23 03:13 UTC, hakuturu583 commented on simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
> +  return distance <= range;
This comment about very small code styling, so I approve this PR.

2023-08-23 03:54 UTC, merged