feat(follow_trajectory): add follow waypoint controller
tier4/scenario_simulator_v2 pull request #1129
Opened 2023-11-13 21:49 UTC by dmoszynski

## Types of PR

- [x] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Link to the issue

## Description

## How to review this PR.

## Others

2023-11-27 11:09 UTC, yamacir-kit requested changes
The pull request description and behavior itself were good.

I understand that this is work-in-progress code, including a later pull request, but even taking that into account the code doesn't seem polished enough.
The behavior was correct, so I think it's just that I don't understand the code enough, and that the algorithm itself is correct. After I return this review, I'll take a break and try reading the code again.

I also found a behavior that seems to be a bug. After FollowTrajectoryAction ends, the entity instantly points in the direction of the X-axis of the world coordinate system. This behavior is seen in multiple test scenarios, most notably in RoutingAction.FollowTrajectoryAction-autoware.yaml. This behavior is probably not a direct result of the changes in this pull request, but rather a latent bug that has surfaced as a result of the changes in this pull request.

2023-11-29 03:43 UTC, yamacir-kit requested changes

2023-11-29 03:43 UTC, yamacir-kit commented on simulation/traffic_simulator/src/behavior/follow_waypoint_controller.cpp
> +  local_min_acc = std::max(local_min_acc, acceleration - max_deceleration_rate * step_time);
```suggestion
  const auto local_min_acc = [&]() {
    if (std::abs(speed) < local_epsilon) {
      return 0.0;
    } else if (time_for_non_acc > 0) {
      return (0.0 - speed) / time_for_non_acc;
    } else {
      return std::max(-max_deceleration, acceleration - max_deceleration_rate * step_time);
    }
  }();
```

2023-12-05 19:37 UTC, dmoszynski commented on simulation/traffic_simulator/include/traffic_simulator/behavior/follow_waypoint_controller.hpp
> +  auto straightMove(const double acc, const double step_time) -> void
This was my omission, sorry - corrected

2023-12-05 19:38 UTC, dmoszynski commented on simulation/traffic_simulator/include/traffic_simulator/behavior/follow_waypoint_controller.hpp
> +    acceleration = acc;
Thank you for your feedback, I removed all the shortcuts - I hope.

2023-12-05 19:38 UTC, dmoszynski commented on simulation/traffic_simulator/include/traffic_simulator/behavior/follow_waypoint_controller.hpp
> +  const int number_of_acceleration_candidates{20};
Thank you for your valuable feedback, corrected.

2023-12-05 19:39 UTC, dmoszynski commented on simulation/traffic_simulator/include/traffic_simulator/behavior/follow_waypoint_controller.hpp
> +  const double predicted_distance_tolerance{1.0};
I have added a description of each variable and a heading for their experimental selection.

2023-12-05 19:40 UTC, dmoszynski commented on simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
> +  }
I have modified the structure of the code a little, I hope it is better quality.

2023-12-05 19:41 UTC, dmoszynski commented on simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
> +    vertices.begin(), vertices.end(), [](auto && vertex) { return not std::isnan(vertex.time); });
I've unified it, I hope it's more elegant

2023-12-05 19:42 UTC, dmoszynski commented on simulation/traffic_simulator/src/behavior/follow_waypoint_controller.cpp
> +  const double remaining_time, const double left_distance, const double acceleration,
I've changed to the `remaining_distance`, I hope it's clearer.

2023-12-05 19:43 UTC, dmoszynski commented on simulation/traffic_simulator/src/behavior/follow_waypoint_controller.cpp
> +    static_cast<long long int>(remaining_time_source / step_time);
I have changed to type `std::size_t `and ensured that an exception is thrown if the range is exceeded.

2023-12-05 19:44 UTC, dmoszynski commented on simulation/traffic_simulator/src/behavior/follow_waypoint_controller.cpp
> +  }
I've added a detailed description of this method, I hope this will be helpful.

2023-12-21 01:54 UTC, yamacir-kit approved these changes

2023-12-21 01:55 UTC, merged