Feature/random scenario
tier4/scenario_simulator_v2 pull request #1145
Opened 2023-12-04 09:55 UTC by hakuturu583

## Types of PR

- [x] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Link to the issue

## Description

- Add random scenario example.
- Enable spawn ego entity in C++ scenarios.

## How to review this PR.

Please check passing all CI tests.

## Others

2023-12-06 05:13 UTC, HansRobo requested changes
Could you add a sammary of chages to to the release note?
(especially about API changes)

2023-12-06 09:17 UTC, HansRobo commented on mock/cpp_mock_scenarios/src/random_scenario/random001.cpp
> +    [&]() {
Why to use a lambda function here?
I think there is no advantage to use lambda function here than {} to limit scope.

2023-12-06 09:18 UTC, HansRobo commented on mock/cpp_mock_scenarios/src/random_scenario/random001.cpp
> +    [&]() {
Why to use a lambda function here?
I think there is no advantage to use lambda function here than {} to limit scope.

2023-12-06 09:19 UTC, HansRobo commented on mock/cpp_mock_scenarios/src/random_scenario/random001.cpp
> +    }();
Why to use a lambda function here?
I think there is no advantage to use lambda function here than {} to limit scope.

2023-12-06 09:22 UTC, HansRobo commented on mock/cpp_mock_scenarios/launch/mock_test.launch.py
> +    vehicle_model = LaunchConfiguration("vehicle_model", default="jpntaxi")
jpntaxi is not public vehicle description.
In OSS perspective, it is good for default value to use a public vehicle description like lexus or sample_vehicle.

2023-12-07 01:05 UTC, hakuturu583 commented on mock/cpp_mock_scenarios/src/random_scenario/random001.cpp
> +    }();
Yes, I used the lambda function in order to limit the scope.

2023-12-07 01:40 UTC, HansRobo commented on mock/cpp_mock_scenarios/launch/mock_test.launch.py
> +    vehicle_model = LaunchConfiguration("vehicle_model", default="jpntaxi")
@hakuturu583 If you use `sample_vehicle`, you should use `sample_sensor_kit` as sensor_model.

2023-12-07 01:59 UTC, HansRobo approved these changes
LGTM, waiting for green CIs.

2023-12-07 06:44 UTC, merged