Consider road slope in ego vehicle simulation
tier4/scenario_simulator_v2 pull request #1182
Opened 2024-02-01 01:10 UTC by HansRobo

## Types of PR

- [ ] New Features
- [x] Upgrade of existing features
- [ ] Bugfix

## Link to the issue

https://github.com/autowarefoundation/autoware.universe/pull/4941
https://github.com/autowarefoundation/autoware.universe/pull/5199
https://github.com/autowarefoundation/autoware.universe/pull/5501
https://github.com/autowarefoundation/autoware.universe/pull/5616

## Description

## How to review this PR.

## Others

2024-02-08 07:42 UTC, HansRobo commented
Waiting for #1184

2024-02-21 07:06 UTC, hakuturu583 requested changes

2024-02-21 07:06 UTC, hakuturu583 commented on simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
> +  const auto vel_time_delay             = getParameter<double>("vel_time_delay",              0.1);  // 0.25 is default value on simple_planning_simulator
```suggestion
  const auto vel_time_constant          = getParameter<double>("vel_time_constant",           0.1);  // @note 0.5 is default value on simple_planning_simulator
  const auto vel_time_delay             = getParameter<double>("vel_time_delay",              0.1);  // @note 0.25 is default value on simple_planning_simulator
```

2024-02-21 07:06 UTC, hakuturu583 commented on simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
> +  // the lanelet matching algorithm should be equivalent to the one used in EgoEntity::setMapPose
```suggestion
  // @note The lanelet matching algorithm should be equivalent to the one used in EgoEntity::setMapPose
```

2024-02-21 07:06 UTC, hakuturu583 commented on simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
> +  // copied from motion_util::findNearestSegmentIndex
```suggestion
  // @note Copied from motion_util::findNearestSegmentIndex
```

2024-02-21 07:06 UTC, hakuturu583 commented on simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
> +  // copied from motion_util::findNearestSegmentIndex
Please show the permalink of the Autoware code you referenced using the @sa command in Doxygen.

2024-02-21 07:06 UTC, hakuturu583 commented on simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
> +  // calculate ego yaw angle on lanelet coordinates
```suggestion
  // @note Calculate ego yaw angle on lanelet coordinates
```

2024-02-21 07:06 UTC, hakuturu583 commented on simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
> +  // calculate ego pitch angle considering ego yaw.
```suggestion
  // @note calculate ego pitch angle considering ego yaw.
```

2024-02-21 07:06 UTC, hakuturu583 commented on simulation/traffic_simulator/src/entity/ego_entity.cpp
> +  // the lanelet matching algorithm should be equivalent to the one used in EgoEntitySimulation::getMatchedLaneletPoseFromEntityStatus
```suggestion
  // @note The lanelet matching algorithm should be equivalent to the one used in EgoEntitySimulation::getMatchedLaneletPoseFromEntityStatus
```

2024-02-22 02:52 UTC, hakuturu583 approved these changes

2024-02-22 02:52 UTC, merged