Feature/openscenario validator
tier4/scenario_simulator_v2 pull request #1228
Opened 2024-04-11 10:22 UTC by HansRobo

# Description

> Please check examples and comment out this sentence. Minimal example is [here](pull_request_samples/example_simple.md) and detailed example is [here](pull_request_samples/example_detail.md)

## Abstract

> [Required] This section is required, keep it short, clear and to the point.  
> Delete this sentence and explain this pull request shortly.  

## Background

> [Optional] If there is no background information that needs explanation (e.g., just a typo correction, etc.), you can skip this section.  
> Delete this sentence and explain the circumstances that led to this pull request being sent.  

## Details

> [Optional] If there are only differences whose effects are so obvious that no explanation is needed, or if there are no differences in the code (e.g., documentation additions), you can skip this section.  
> Delete this sentence and describe this pull request.  
> For example, it is desirable to describe the specifications of added functions, and detailed explanations of bugs that have been fixed.  

## References

> [Optional] If the referenced material does not exist, you can skip this section.  
> Describe any standards, algorithms, books, articles, etc. that you referenced when creating the pull request. If there is any novelty, mention it.  

# Destructive Changes

> [Optional] If no destructive change exists, you can skip this section.  
> Include a description of the changes and a migration guide and send the pull request with a bump major label. (Example : https://github.com/tier4/scenario_simulator_v2/pull/1139)  
> Otherwise, skip the "Destructive Changes" section and make sure this pull request is labeled `bump minor` or `bump patch`.  

# Known Limitations

> [Optional] If there are no known limitations that you can think of, you can skip this section. If there are any limitations on the features or fixes added by this pull request, delete this sentence and clearly describe them.
> For example, the lane matching algorithm currently (1/25/2024) employed is unable to match Entity that is heavily tilted with respect to the lane, and it is difficult to throw an exception.  
> If the developer is aware of the existence of such problems or limitations, describe them in detail. The problems or limitation should be listed as an Issue on GitHub and a link to it should be provided in this section.

2024-04-22 04:05 UTC, yamacir-kit requested changes

2024-04-22 04:39 UTC, HansRobo commented on openscenario/openscenario_validator/CMakeLists.txt
> +  src/validator.cpp)
> Unless this package is intended to be used as a C++ library

This is the original purpose of this package, and the executable is OK even if it doesn't exist.

2024-04-23 02:42 UTC, HansRobo commented on openscenario/openscenario_validator/include/openscenario_validator/validator.hpp
> +static XMLPlatform platform{};
Fied in https://github.com/tier4/scenario_simulator_v2/pull/1228/commits/bc0928d8cd9a393ae87f8e36230b002fbcfdfcb6

2024-04-23 02:43 UTC, HansRobo commented on openscenario/openscenario_validator/CMakeLists.txt
> +  src/validator_command.cpp)
Fixed in https://github.com/tier4/scenario_simulator_v2/pull/1228/commits/73bc5303b23ed9e5c5ddb82807ae5fae41108c0a

2024-05-16 09:21 UTC, yamacir-kit approved these changes

2024-05-16 09:22 UTC, merged