RJD-1197/distance
tier4/scenario_simulator_v2 pull request #1366
Opened 2024-09-09 10:31 UTC by robomic

# Description

## Abstract

This PR contains unit tests for the distance namespace, which is a part of traffic_simulator package.
Additionally: 
- **Minor fixes were applied to the `distanceToLeftLaneBound` and `distanceToRightLaneBound`.**
- The standard map, which was used extensively, was moved into its own folder, just like the other maps.
- Minor simplifications in the old `hdmap_utils` tests.
- An additional map `intersection` was added. It contains a large, complex intersection and is convenient in numerous scenarios.

## Details
List of tests included in this PR:

1. distanceTest_FourTrackHighway.lateralDistance_impossible_noChange
2. distanceTest_FourTrackHighway.lateralDistance_possible_noChange
3. distanceTest_FourTrackHighway.lateralDistance_impossible_change
4. distanceTest_FourTrackHighway.lateralDistance_possible_change
5. distanceTest_FourTrackHighway.lateralDistance_impossible_matching
6. distanceTest_FourTrackHighway.lateralDistance_possible_matching
7. distanceTest_FourTrackHighway.longitudinalDistance_noAdjacent_noOpposite_noChange_false
8. distanceTest_FourTrackHighway.longitudinalDistance_adjacent_noOpposite_noChange_false
9. distanceTest_FourTrackHighway.longitudinalDistance_adjacent_noOpposite_noChange
10. distanceTest_FourTrackHighway.longitudinalDistance_noAdjacent_noOpposite_change_false
11. distanceTest_FourTrackHighway.longitudinalDistance_noAdjacent_noOpposite_change
12. distanceTest_StandardMap.longitudinalDistance_noAdjacent_noOpposite_noChange
13. distanceTest_StandardMap.distanceToLeftLaneBound_single
14. distanceTest_StandardMap.distanceToLeftLaneBound_multipleVector
15. distanceTest_StandardMap.distanceToLeftLaneBound_singleVector
16. distanceTest_StandardMap.distanceToLeftLaneBound_emptyVector
17. distanceTest_Intersection.longitudinalDistance_adjacent_noOpposite_change_false
18. distanceTest_Intersection.longitudinalDistance_adjacent_noOpposite_change
19. distanceTest_Intersection.distanceToRightLaneBound_single
20. distanceTest_Intersection.distanceToRightLaneBound_multipleVector
21. distanceTest_Intersection.distanceToRightLaneBound_singleVector
22. distanceTest_Intersection.distanceToRightLaneBound_emptyVector
23. distance.boundingBoxDistance_intersection
24. distance.boundingBoxDistance_disjoint

## References
Jira ticket: [internal link](https://tier4.atlassian.net/browse/RJD-1197)

# Destructive Changes

There are no destructive changes.

# Regression tests
Jira comment: [internal link](https://tier4.atlassian.net/browse/RJD-1197?focusedCommentId=186230)

2024-09-10 01:34 UTC, hakuturu583 requested changes
It seems, you changed the behavior of the functions in traffic_simulator.
So, please run regression test before pull request open.

2024-09-10 01:34 UTC, hakuturu583 commented on simulation/traffic_simulator/src/utils/distance.cpp
> +  }
It seems, you changed the behavior of the functions in traffic_simulator.
So, please run regression test before pull request open.

2024-09-12 09:20 UTC, robomic commented
Regression tests: [internal link](https://tier4.atlassian.net/browse/RJD-1197?focusedCommentId=186230)

2024-09-19 02:50 UTC, hakuturu583 approved these changes

2024-09-19 02:50 UTC, merged