Reducing build time of `openscenario_interpreter` by utilizing precompiled headers
tier4/scenario_simulator_v2 pull request #1370
Opened 2024-09-10 09:00 UTC by shouth

# Description

## Abstract

This pull request reduces the build time for `opendscenario_interpreter` by using precompiled headers.

## Background

In the current codebase, large header files were being parsed multiple times and cause longer build time. To address this, I used Clang's `-ftime-trace` to identify the headers that were taking the most time to parse and updated `CMakeLists.txt` to ensure they are precompiled.

## Details

In my environment, the build time of `openscenario_interpreter` was reduced from 9m 21s to 7m 59s with 12 parallel builds.

## References

N/A

# Destructive Changes

N/A

# Known Limitations

N/A

2024-09-25 02:47 UTC, yamacir-kit requested changes

2024-09-25 02:47 UTC, yamacir-kit commented on openscenario/openscenario_interpreter/CMakeLists.txt
> +    "<openscenario_interpreter/simulator_core.hpp>")
Please sort lexicographically, unless there is a technical reason why declaration order matters. Also, please remove blank lines.

2024-09-25 02:52 UTC, yamacir-kit commented
I have confirmed that the openscenario_interpreter build is 3 minutes shorter in GitHub Actions as well.

2024-10-10 00:57 UTC, shouth commented
I sorted precompiled header list.

2024-10-10 05:06 UTC, yamacir-kit approved these changes

2024-10-10 05:06 UTC, merged