RJD-1457/traffic_sink_refactor
tier4/scenario_simulator_v2 pull request #1464
Opened 2024-11-28 16:30 UTC by robomic

To be added

2024-12-13 02:20 UTC, hakuturu583 requested changes

2024-12-13 02:20 UTC, hakuturu583 commented on mock/cpp_mock_scenarios/launch/mock_test.launch.py
This file is written in a way that it cannot be formatted to align line and variable heads.
If you do not need it, please modify it to the original format.

2024-12-13 02:20 UTC, hakuturu583 commented on simulation/traffic_simulator/src/traffic/traffic_sink.cpp
> +  for (const auto & entity_name : entity_names) {
```suggestion
  for (const auto & entity_name : entity_manager_ptr_->getEntityNames()) {
```

2024-12-18 10:54 UTC, robomic commented on mock/cpp_mock_scenarios/launch/mock_test.launch.py
the differences were from this [PR](https://github.com/tier4/scenario_simulator_v2/pull/1443/files); my work was based on these initial changes. I have reverted almost all format changes

2024-12-20 09:43 UTC, hakuturu583 approved these changes
LGTM

2024-12-20 09:46 UTC, hakuturu583 commented
Since this PR is a continuation of #1443, I am currently checking with the reviewer of the original PR, @yamacir-kit, to see if a review by him is needed.

2024-12-23 08:06 UTC, merged