Relative target speed
tier4/scenario_simulator_v2 pull request #320
Opened 2021-05-27 09:02 UTC by kyabe2718

## Types of PR

- [x] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Link to the issue

## Description
add support for RelativeTargetSpeed

## How to review this PR.

## Others

2021-06-16 04:05 UTC, hakuturu583 commented
Convert to draft because of #358

2021-06-16 06:58 UTC, hakuturu583 requested changes
Code looks good to me, please add this changes to the ReleaseNote

2021-06-17 08:09 UTC, yamacir-kit approved these changes

2021-06-17 08:40 UTC, hakuturu583 requested changes

2021-06-17 08:40 UTC, hakuturu583 commented on docs/ReleaseNotes.md
> +- Add support for RelativeTargetSpeed, the syntax of OpenSCENARIO
It seems, this file is different from master branch.

2021-06-18 03:32 UTC, hakuturu583 commented
I fixed relase notes!

2021-06-18 03:33 UTC, hakuturu583 approved these changes

2021-06-18 03:59 UTC, merged