Add arrow markers to visualize goal poses of entities
tier4/scenario_simulator_v2 pull request #458
Opened 2021-08-20 07:33 UTC by Utaro-M

## Types of PR

- [x] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Link to the issue

## Description
Add arrow markers to visualize goal poses of entities
## How to review this PR.

## Others

2021-08-20 07:46 UTC, hakuturu583 requested changes
Typo was detected, so please fix goal poses variable name.

2021-08-20 07:46 UTC, hakuturu583 commented on openscenario/openscenario_msgs/msg/EntityStatusWithTrajectory.msg
> +geometry_msgs/Pose[] goalposes
can you rename to goal_poses ?
goalposes was detected as typo.

2021-08-20 07:46 UTC, hakuturu583 commented on openscenario/openscenario_visualization/include/openscenario_visualization/openscenario_visualization_component.hpp
> +    const std::vector<geometry_msgs::msg::Pose> & goalposes,
can you rename to goal_poses ?
goalposes was detected as typo in other line.

2021-08-20 07:46 UTC, hakuturu583 commented on openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
> +      generateMarker(data.status, data.goalposes, data.waypoint, data.obstacle, data.obstacle_find);
can you rename to goal_poses ?
goalposes was detected as typo in other line.

2021-08-20 07:46 UTC, hakuturu583 commented on openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
> +  const std::vector<geometry_msgs::msg::Pose> & goalposes,
can you rename to goal_poses ?
goalposes was detected as typo in other line.

2021-08-20 07:46 UTC, hakuturu583 commented on simulation/traffic_simulator/include/traffic_simulator/behavior/route_planner.hpp
> +  std::vector<openscenario_msgs::msg::LaneletPose> getGoalposes();
Can you change to getGoalPoses ?

2021-08-20 07:46 UTC, hakuturu583 commented on simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
> +  virtual auto getGoalposes() ->  std::vector<openscenario_msgs::msg::LaneletPose> =0;
Can you change to getGoalPoses ?

2021-08-20 07:46 UTC, hakuturu583 commented on simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
> +  void getGoalposes(const std::string & name, std::vector<openscenario_msgs::msg::LaneletPose> & goals);
Can you change to getGoalPoses ?

2021-08-20 07:46 UTC, hakuturu583 commented on simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
> +  void getGoalposes(const std::string & name, std::vector<geometry_msgs::msg::Pose> & goals);
Can you change to getGoalPoses ?

2021-08-20 07:46 UTC, hakuturu583 commented on simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
> +  std::vector<openscenario_msgs::msg::LaneletPose> getGoalposes() override { return {}; } //return {}?
Can you change to getGoalPoses ?

2021-08-20 07:46 UTC, hakuturu583 commented on simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
> +  std::vector<openscenario_msgs::msg::LaneletPose> getGoalposes() override { return route_planner_ptr_->getGoalposes(); }
Can you change to getGoalPoses ?

2021-08-20 07:46 UTC, hakuturu583 commented on simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
> +  std::vector<openscenario_msgs::msg::LaneletPose> getGoalposes() override { return route_planner_ptr_->getGoalposes(); }
Can you change to getGoalPoses ?

2021-08-20 07:46 UTC, hakuturu583 commented on simulation/traffic_simulator/src/entity/entity_manager.cpp
> +void EntityManager::getGoalposes(const std::string & name, std::vector<openscenario_msgs::msg::LaneletPose> & goals)
Can you change to getGoalPoses ?

2021-08-20 07:46 UTC, hakuturu583 commented on simulation/traffic_simulator/src/entity/entity_manager.cpp
> +void EntityManager::getGoalposes(const std::string & name, std::vector<geometry_msgs::msg::Pose> & goals)
Can you change to getGoalPoses ?

2021-08-20 11:31 UTC, Utaro-M reviewed
修正してpushしました。
よろしくお願いします。

2021-08-23 02:01 UTC, hakuturu583 requested changes
Some word was detected as typo in spell checker, so please change wordings.

2021-08-23 02:01 UTC, hakuturu583 commented on simulation/traffic_simulator/src/behavior/route_planner.cpp
> +  std::vector<openscenario_msgs::msg::LaneletPose> goalposes;
goalposes was detected as typo in spellcheck.
Please modify to goal_poses

2021-08-23 02:03 UTC, hakuturu583 requested changes

2021-08-23 02:03 UTC, hakuturu583 commented on docs/ReleaseNotes.md
> +- Add arrow markers to visualize goal poses of entities.
please adding your github account like

> Add a new metrics module which detects vel, acc and jerk out of range. (Contribution by kyabe2718).

2021-09-01 04:49 UTC, hakuturu583 commented
> 修正してpushしました。
> よろしくお願いします。

please use english in Pull request.

2021-09-03 05:14 UTC, hakuturu583 requested changes
Miss-spelled worlds are still exists.
Please fix typos.

2021-09-03 05:14 UTC, hakuturu583 commented on openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
> +        visualization_msgs::msg::Marker goalpose_marker;
It seems, this miss-spell was not fixed yet.

2021-09-03 05:14 UTC, hakuturu583 commented on openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
> +        goalpose_marker.ns = status.name;
It seems, this miss-spell was not fixed yet.

2021-09-03 05:14 UTC, hakuturu583 commented on openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
> +        goalpose_marker.header.frame_id = "map";
It seems, this miss-spell was not fixed yet.

2021-09-03 05:14 UTC, hakuturu583 commented on openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
> +        goalpose_marker.header.stamp = stamp;
It seems, this miss-spell was not fixed yet.

2021-09-03 05:14 UTC, hakuturu583 commented on simulation/traffic_simulator/src/behavior/route_planner.cpp
> +  std::vector<openscenario_msgs::msg::LaneletPose> goalposes;
It seems, this miss-spell was not fixed yet.

2021-09-03 05:14 UTC, hakuturu583 commented on simulation/traffic_simulator/src/behavior/route_planner.cpp
> +  goalposes = {};
It seems, this miss-spell was not fixed yet.

2021-09-03 05:14 UTC, hakuturu583 commented on simulation/traffic_simulator/src/behavior/route_planner.cpp
> +    goalposes.push_back(waypoint_queue_tmp_.front());
It seems, this miss-spell was not fixed yet.

2021-09-03 05:14 UTC, hakuturu583 commented on simulation/traffic_simulator/src/behavior/route_planner.cpp
> +  return goalposes;
It seems, this miss-spell was not fixed yet.

2021-09-06 11:36 UTC, hakuturu583 approved these changes
spell check will be cleaned later, so I merge this PR first.

2021-09-06 11:37 UTC, merged