Set name in the proto request for non-ego vehicles
tier4/scenario_simulator_v2 pull request #486
Opened 2021-08-31 12:40 UTC by prybicki

In the previous PR I forgot to set the name in all if-branches when spawning a vehicle.
Noticed that the code is largely the same for both branches, so I propose to simplify this code to avoid future mistakes like mine. The code logic should be preserved, only set_is_ego is moved after toProto() (pure subjective aesthetics), which should not affect semantics.

## Types of PR

- [ ] New Features
- [ ] Upgrade of existing features
- [x] Bugfix

## Link to the issue

## Description

## How to review this PR.

## Others

2021-09-01 01:38 UTC, hakuturu583 requested changes
Thank you for sending PR to our project.
Your code looks good, but clang-format detects code format error.

```
  12: Test command: /usr/bin/python3 "-u" "/opt/ros/galactic/share/ament_cmake_test/cmake/run_test.py" "/home/runner/work/scenario_simulator_v2/scenario_simulator_v2/ros_ws/build/traffic_simulator/test_results/traffic_simulator/test_collision.gtest.xml" "--package-name" "traffic_simulator" "--output-file" "/home/runner/work/scenario_simulator_v2/scenario_simulator_v2/ros_ws/build/traffic_simulator/ament_cmake_gtest/test_collision.txt" "--command" "/home/runner/work/scenario_simulator_v2/scenario_simulator_v2/ros_ws/build/traffic_simulator/test/src/math/test_collision" "--gtest_output=xml:/home/runner/work/scenario_simulator_v2/scenario_simulator_v2/ros_ws/build/traffic_simulator/test_results/traffic_simulator/test_collision.gtest.xml"
  12: Test timeout computed to be: 60
  12: -- run_test.py: invoking following command in '/home/runner/work/scenario_simulator_v2/scenario_simulator_v2/ros_ws/build/traffic_simulator/test/src/math':
  12:  - /home/runner/work/scenario_simulator_v2/scenario_simulator_v2/ros_ws/build/traffic_simulator/test/src/math/test_collision --gtest_output=xml:/home/runner/work/scenario_simulator_v2/scenario_simulator_v2/ros_ws/build/traffic_simulator/test_results/traffic_simulator/test_collision.gtest.xml
  12: [==========] Running 3 tests from 1 test suite.
  12: [----------] Global test environment set-up.
  12: [----------] 3 tests from Collision
  12: [ RUN      ] Collision.DifferentHeight
  12: [       OK ] Collision.DifferentHeight (0 ms)
  12: [ RUN      ] Collision.SamePosition
  12: [       OK ] Collision.SamePosition (2 ms)
  12: [ RUN      ] Collision.SameHeightNoCollision
  12: [       OK ] Collision.SameHeightNoCollision (1 ms)
  12: [----------] 3 tests from Collision (3 ms total)
  12: 
  12: [----------] Global test environment tear-down
  12: [==========] 3 tests from 1 test suite ran. (3 ms total)
  12: [  PASSED  ] 3 tests.
  12: -- run_test.py: return code 0
  12: -- run_test.py: inject classname prefix into gtest result file '/home/runner/work/scenario_simulator_v2/scenario_simulator_v2/ros_ws/build/traffic_simulator/test_results/traffic_simulator/test_collision.gtest.xml'
  12: -- run_test.py: verify result file '/home/runner/work/scenario_simulator_v2/scenario_simulator_v2/ros_ws/build/traffic_simulator/test_results/traffic_simulator/test_collision.gtest.xml'
  12/12 Test #12: test_collision ...................   Passed    0.18 sec
  
  92% tests passed, 1 tests failed out of 12
  
  Label Time Summary:
  clang_format    =   3.14 sec*proc (1 test)
  copyright       =  15.55 sec*proc (1 test)
  gtest           =   6.40 sec*proc (8 tests)
  lint_cmake      =   0.42 sec*proc (1 test)
  linter          =  19.55 sec*proc (4 tests)
  xmllint         =   0.44 sec*proc (1 test)
  
  Total Test time (real) =  25.97 sec
  
  The following tests FAILED:
  	  1 - clang_format (Failed)
```

can you execute commands below?
```
cd (directory of scenario_simulator_v2)
ament_clang_format --reformat
```

2021-09-06 08:38 UTC, hakuturu583 commented
@prybicki friendly ping

2021-09-06 10:13 UTC, prybicki commented
```
cd (directory of scenario_simulator_v2)
ament_clang_format --reformat
```
Done. Sorry for the delay.

2021-09-06 11:32 UTC, hakuturu583 approved these changes
LGTM! Thank you for your contribution!

2021-09-06 11:32 UTC, merged