Traffic lights ZMQ API
tier4/scenario_simulator_v2 pull request #530
Opened 2021-09-22 10:48 UTC by pijaro

## Types of PR

- [x] New Features
- [x] Upgrade of existing features
- [ ] Bugfix

## Description

Adds ZMQ API for traffic lights control.

2021-09-22 12:13 UTC, hakuturu583 requested changes
Code looks good.
Can you fix typos?

2021-09-22 12:13 UTC, hakuturu583 commented on simulation/simulation_interface/include/simulation_interface/constants.hpp
> +const unsigned int update_traffic_ligths = 5565;
Typo was detected.

2021-09-22 12:13 UTC, hakuturu583 commented on simulation/simulation_interface/src/zmq_multi_server.cpp
> +    protocol, hostname, simulation_interface::ports::update_traffic_ligths));
typo was detected

2021-09-22 12:13 UTC, hakuturu583 commented on simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
> +      simulation_interface::ports::update_traffic_ligths)
typo was detected

2021-09-22 12:13 UTC, hakuturu583 commented on simulation/traffic_simulator/src/api/api.cpp
> +      auto traf_light = entity_manager_ptr_->getTrafficLightInstance(id);
This word was detected as typo.
Can you fix to traffic_light?

2021-09-22 12:13 UTC, hakuturu583 commented on simulation/traffic_simulator/src/api/api.cpp
> +        static_cast<const autoware_perception_msgs::msg::TrafficLightState>(traf_light), state);
This word was detected as typo.
Can you fix to traffic_light?

2021-09-27 09:52 UTC, pijaro commented
@hakuturu583 Typos should be fixed now. Sorry for that :bow:

2021-09-27 14:36 UTC, hakuturu583 approved these changes
Great work!
Thank you!

2021-09-27 14:36 UTC, merged