Refactor/interpreter/reference
tier4/scenario_simulator_v2 pull request #605
Opened 2021-11-09 03:14 UTC by yamacir-kit

## Types of PR

- [ ] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Link to the issue

## Description

## How to review this PR.

## Others

2021-11-11 10:07 UTC, hakuturu583 requested changes

2021-11-11 10:07 UTC, hakuturu583 commented on openscenario/openscenario_interpreter/include/openscenario_interpreter/name.hpp
> +      os << (prefix.empty() ? "{annonymous}" : prefix.c_str()) << "::";
Is it "anonymous"?

2021-11-11 10:07 UTC, hakuturu583 commented on openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
> +  auto lookdown(const std::string &) const -> Object;
I think look up and look down is two words.
So, I suggest to use "lookDown"

2021-11-11 15:12 UTC, yamacir-kit commented on openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
> +  auto lookdown(const std::string &) const -> Object;
There seems to be no problem with just one word.
https://wikidiff.com/lookdown/lookup

2021-11-11 15:14 UTC, yamacir-kit commented on openscenario/openscenario_interpreter/include/openscenario_interpreter/name.hpp
> +      os << (prefix.empty() ? "{annonymous}" : prefix.c_str()) << "::";
08ea9ae fixed this.

2021-11-12 00:34 UTC, kmiya commented on openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
> +  auto lookdown(const std::string &) const -> Object;
FYI: On Wikipedia, Lookdown seems to be used as a fish name (シロガネアジ in Japanese).
<https://en.wiktionary.org/wiki/File:Selene_vomer_03_by_Line1.JPG>

Could not find the word in the other famous dictionaries such as [Cambridge](https://dictionary.cambridge.org/spellcheck/english/?q=lookdown) and [Oxford](https://www.oxfordlearnersdictionaries.com/spellcheck/english/?q=lookdown).

2021-11-12 01:55 UTC, hakuturu583 approved these changes

2021-11-12 01:57 UTC, hakuturu583 requested changes
Sorry, still this problem remains.
https://github.com/tier4/scenario_simulator_v2/pull/605#discussion_r747903348

2021-11-12 04:28 UTC, hakuturu583 approved these changes

2021-11-12 04:28 UTC, merged