Feature/zmqpp vendor
tier4/scenario_simulator_v2 pull request #778
Opened 2022-05-12 05:37 UTC by hakuturu583

## Types of PR

- [ ] New Features
- [x] Upgrade of existing features
- [ ] Bugfix

## Link to the issue

## Description

add zmqpp_vendor package for future humble support.

## How to review this PR.

please check passing all CI tests.

## Others

2022-05-20 05:40 UTC, HansRobo requested changes
LGTM about your addition!
But some old ignores remains.

2022-05-20 05:40 UTC, HansRobo commented on .gitignore
>  external/mrt_cmake_modules
```suggestion
```
ココらへんもついでに消しませんか？
[reposファイル]([https://github.com/tier4/scenario_simulator_v2/blob/feature/zmqpp_vendor/dependency_galactic.repos)によると](https://github.com/tier4/scenario_simulator_v2/blob/feature/zmqpp_vendor/dependency_galactic.repos)%E3%81%AB%E3%82%88%E3%82%8B%E3%81%A8)，
- autoware_auto_msgs
- tier4_msgs
- zmqpp_vendor
だけ回避すれば大丈夫そうです

2022-05-20 05:53 UTC, HansRobo approved these changes

2022-05-24 03:33 UTC, hakuturu583 commented
Waiting for Autoware will be ready.

2022-06-08 03:47 UTC, merged