Feature/use GitHub registry
tier4/scenario_simulator_v2 pull request #844
Opened 2022-07-25 03:35 UTC by hakuturu583

## Types of PR

- [ ] New Features
- [x] Upgrade of existing features
- [ ] Bugfix

## Link to the issue

#843 

## Description

## How to review this PR.

Please check passing all CI tests.

## Others

2022-07-26 09:41 UTC, HansRobo requested changes
Please fix the documentation.
I tried running the modified commands in `RunWithDocker.md`, but even `docker pull` didn't succeed

2022-07-27 01:37 UTC, hakuturu583 commented
> Please fix the documentation.
> 
> I tried running the modified commands in `RunWithDocker.md`, but even `docker pull` didn't succeed

This is because docker image does not published at container registry.

2022-07-27 01:44 UTC, HansRobo approved these changes

2022-07-27 01:45 UTC, HansRobo commented
I see.
I will check the links after merging this.

2022-07-27 01:45 UTC, merged