Fix/AJD-653 map path files
tier4/scenario_simulator_v2 pull request #966
Opened 2023-02-01 13:00 UTC by dmoszynski

## Types of PR

- [ ] New Features
- [ ] Upgrade of existing features
- [x] Bugfix

## Link to the issue
https://tier4.atlassian.net/browse/AJD-653?atlOrigin=eyJpIjoiYzgyM2I2OTAzYzUzNDcwNGExOWJlYjJlZDhkMGM1MzYiLCJwIjoiaiJ9

## Description
Two changes were introduced:
- Throwing an exception for missing `*.osm` file in map path has been uncommented.
- The situation with exception handling before `SimulationCore` is `activated` (or after it was `deactivated`) has been fixed - in this case getting simulation time is not possible.

## How to review this PR.

## Others
Regression tests have been done, details of the analysis are described here:
- https://tier4.atlassian.net/browse/AJD-658?focusedCommentId=112243
- https://tier4.atlassian.net/browse/AJD-658?focusedCommentId=112241

Tsutake-san has made sure the results of regression tests.

2023-02-02 05:30 UTC, HansRobo commented
@dmoszynski Could you merge the latest master branch into this branch first?
That will eliminate one cause of the BuildTest failures.

2023-02-02 07:53 UTC, dmoszynski commented
> @dmoszynski Could you merge the latest master branch into this branch first? That will eliminate one cause of the BuildTest failures.

Sure, done.

2023-02-06 08:59 UTC, adamdbrw commented
@yamacir-kit could you please take a look? Thank you!

2023-02-07 02:35 UTC, yamacir-kit requested changes

2023-02-07 02:35 UTC, yamacir-kit commented on openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
> +        return std::numeric_limits<double>::quiet_NaN();
```suggestion
      if (SimulatorCore::active()) {
        return core->getCurrentTime(std::forward<decltype(xs)>(xs)...);
      } else {
        return std::numeric_limits<double>::quiet_NaN();
      }
```

2023-02-07 02:35 UTC, yamacir-kit commented on simulation/traffic_simulator/include/traffic_simulator/api/configuration.hpp
>      else {
Please change the style according to the error message on https://github.com/tier4/scenario_simulator_v2/actions/runs/4072331531/jobs/7014974239.

2023-02-07 02:45 UTC, yamacir-kit commented on openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
> +        return std::numeric_limits<double>::quiet_NaN();
(There is no problem with the contents of the code)

2023-02-09 07:45 UTC, yamacir-kit approved these changes

2023-02-09 07:45 UTC, merged