fix(beh_tree_plug): fix target_speed init in MoveBackwardAction
tier4/scenario_simulator_v2 pull request #968
Opened 2023-02-06 00:35 UTC by dmoszynski

## Types of PR

- [ ] New Features
- [ ] Upgrade of existing features
- [x] Bugfix

## Link to the issue

## Description
Problem:
![image](https://user-images.githubusercontent.com/121798334/216856042-706d80d9-30b2-4ae4-a5e6-d14c17c4a503.png)

The problem was related to the sometimes missing initialization of the `target_seed` variable during the tick of `MoveBackwordAction`.

- I’ve added a check before using it, if the variable is already initialized.
- If it isn't then it is assigned a value with is calculated on the basis of previous lanelets - because it's `MoveBackwordAction`.
- The changes I’ve made are based on other actions implemented in the `behavior_tree_plugin` package (there are analogous checks).

Details and tests: https://tier4.atlassian.net/browse/AJD-658?focusedCommentId=112178

## How to review this PR.

## Others
Regression tests: 
https://tier4.atlassian.net/browse/AJD-658?focusedCommentId=112334
https://tier4.atlassian.net/browse/AJD-658?focusedCommentId=112437
https://tier4.atlassian.net/browse/AJD-658?focusedCommentId=112801

2023-02-06 00:55 UTC, hakuturu583 requested changes

2023-02-06 00:55 UTC, hakuturu583 commented on simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/move_backward_action.cpp
> +  auto following_lanelets =
Isn't it a previous_lanelet?

2023-02-06 00:55 UTC, hakuturu583 commented on simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/move_backward_action.cpp
> +    target_speed = hdmap_utils->getSpeedLimit(following_lanelets);
```
target_speed = hdmap_utils->getSpeedLimit(
  hdmap_utils->getPreviousLanelets(entity_status.lanelet_pose.lanelet_id));
```

Is better.

2023-02-07 06:27 UTC, hakuturu583 commented
@dmoszynski Please use

ament_clang_format --reformat
before pushing your code.

2023-02-07 06:43 UTC, HansRobo commented
the command `ament_clang_format --reformat` doesn't fix errors related to newlines, like `Replace [\n    ] with [ ]`
```
 [src/vehicle/follow_lane_sequence/move_backward_action.cpp:78:27]: Replace [\n    ] with [ ]
    -   auto following_lanelets =
    -     hdmap_utils->getPreviousLanelets(entity_status.lanelet_pose.lanelet_id);
    +   auto following_lanelets = hdmap_utils->getPreviousLanelets(entity_status.lanelet_pose.lanelet_id);
```
I recommend that you manually fix such errors as the error instructed.
Anyway, green ci is needed for merging into master!

2023-02-08 13:06 UTC, dmoszynski reviewed
@hakuturu583 Corrected

2023-02-15 01:39 UTC, hakuturu583 commented
@dmoszynski Thanks, it was bug.

2023-02-15 01:57 UTC, hakuturu583 approved these changes
LGTM

2023-02-15 01:57 UTC, merged