ref(sim_interface): AJD-697 improve zeromq port management - use a single-port
tier4/scenario_simulator_v2 pull request #981
Opened 2023-03-22 12:53 UTC by dmoszynski

## Types of PR

- [] New Features
- [x ] Upgrade of existing features
- [ ] Bugfix

## Link to the issue
https://tier4.atlassian.net/browse/AJD-697

## Description

- I've developed a `single-port` communication and investigated if this affects performance.

- In order to provide `single-port` communication:
  - I've add a [2 universal messages](https://github.com/RobotecAI/scenario_simulator_v2/blob/40e5fa6e8165e52fabd759489f821ef8ad61222a/simulation/simulation_interface/proto/simulation_api_schema.proto#L263-L302) based on Oneof proto message type [(at most one field will be set at the same time - it saves memory)](https://protobuf.dev/programming-guides/proto3/#oneof).  This provided a simple and memory-saving transfer of existing messages on a single port, their identification and easy deserialization:
  - I've adapted [zmq_multi_client](https://github.com/RobotecAI/scenario_simulator_v2/blob/40e5fa6e8165e52fabd759489f821ef8ad61222a/simulation/simulation_interface/src/zmq_multi_client.cpp#L43-L199) to handle universal messages.
  - I've adapted [zmq_mutli_server](https://github.com/RobotecAI/scenario_simulator_v2/blob/40e5fa6e8165e52fabd759489f821ef8ad61222a/simulation/simulation_interface/src/zmq_multi_server.cpp#L99-L180) to handle universal messages.
  - I've removed unnecessary ports (sockets) and their definitions.
  - I left a single port for communication, its value should be given as a rosparm `port` - for `simple_sensor_simulator_node` and `openscenario_interpreter_node`. ([commit](https://github.com/tier4/scenario_simulator_v2/commit/d4473010f5d3de910fac3340af2beecf97771637))

- I’ve developed a `test_zmq_node` ([reverted commit](https://github.com/tier4/scenario_simulator_v2/commit/83c309d2c9885c92221d298be70a692a2a318e3d)) which sends the same data as `traffic_simulator` and it allowed me to test performance in communication with `simple_sensor_simulator`.
## How to review this PR.

## Others

2023-03-30 11:16 UTC, hakuturu583 requested changes
Code looks good to me, please update release note.

2023-03-30 11:16 UTC, hakuturu583 commented on .github/workflows/custom_spell.json
> +}
Please add white line at EOF

2023-03-30 11:16 UTC, hakuturu583 commented on simulation/simulation_interface/proto/simulation_api_schema.proto
> +}
Please add white line at EOF

2023-03-30 18:28 UTC, dmoszynski commented on simulation/simulation_interface/proto/simulation_api_schema.proto
> +}
done

2023-03-31 06:19 UTC, hakuturu583 approved these changes

2023-03-31 06:19 UTC, merged